## <b>Machine Learning

Titanic

In [1]:
import pandas as pd
df= pd.read_csv("/content/drive/MyDrive/datasets/titanic_train.csv")

X= df["Fare"].copy()
X= X.values.reshape(-1, 1)
y= df["Survived"].copy()

In [2]:
from sklearn.linear_model import LogisticRegression
clf= LogisticRegression()
clf.fit(X, y)

LogisticRegression()

In [3]:
clf.score(X, y)

0.6655443322109988

<b> Probabilidade de sobrevivência 0 = Negativa, 1 = Positiva

In [4]:
import numpy as np
clf.predict(np.array([[50]]))

array([0])

In [5]:
clf.predict(np.array([[70]]))

array([1])

<b>O primeiro resultado indica a probabilidade de ocorrer a classe 0 (não sobrevivência), o segundo indica a classe 1 (sobrevivência)

In [6]:
clf.predict_proba(np.array([[50]]))

array([[0.54524709, 0.45475291]])

In [7]:
clf.predict_proba(np.array([[70]]))

array([[0.4694261, 0.5305739]])

<b>Chamando o módulo DataPrep

In [8]:
%run '/content/drive/MyDrive/Colab Notebooks/dataprep_titanic.ipynb'

In [9]:
dp= DataPrep(df)

In [10]:
df_train, df_test= dp.preparar_dados()

In [11]:
X_treino= df_train.drop(columns= "Survived")
y_treino= df_train["Survived"]

X_teste= df_test.drop(columns= "Survived")
y_teste= df_test["Survived"]

In [12]:
clf.fit(X_treino, y_treino)

LogisticRegression()

In [13]:
clf.score(X_teste, y_teste)

0.7873134328358209

<b>Recursive Feature Elimination

In [14]:
from sklearn.feature_selection import RFECV

selector= RFECV(estimator= LogisticRegression())

selector.fit(X_treino, y_treino)

RFECV(estimator=LogisticRegression())

In [15]:
selector.n_features_

5

In [16]:
selector.get_support(indices= True)

array([0, 1, 2, 4, 7])

In [17]:
cols_indices= selector.get_support(indices= True)
cols= X_treino.columns[cols_indices]

In [18]:
X_treino= X_treino[cols]
X_teste= X_teste[cols]

In [19]:
clf.fit(X_treino, y_treino)

LogisticRegression()

In [20]:
clf.score(X_teste, y_teste)

0.7873134328358209